name: Student Report Cron - Main

# CRON time settings
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "5 * * * *" # Run every 5 minutes.
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Create Markdown
    env:
      GH_API_KEY: ${{ secrets.GH_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install -r requirements.txt
          python3 main.py
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add profile/README.md
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
             exit 1
          else
             git commit -m "Add changes"
             echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_API_KEY }}
          branch: master
          force: true
